name: CI
on: 
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run Flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@1
        with:
          distribution: 'adopt'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          chanel: 'stable'
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test